### ISSUE TITLE
IllegalPassedClassDetectorTest.testFindClass:12 Unexpected exception type thrown ==> expected: <org.apache.bcel.classfile.ClassFormatException> but was: <java.lang.NullPointerException>

### ISSUE THREAD

**Issue by vorburger** [KengoTODA/findbugs-slf4j#112]
I'm getting a super weird test failure locally (on Fedora 28 with OpenJDK) : 

```
[INFO] Running jp.skypencil.findbugs.slf4j.IllegalPassedClassDetectorTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in jp.skypencil.findbugs.slf4j.IllegalPassedClassDetectorTest
[ERROR] testFindClass  Time elapsed: 0 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <org.apache.bcel.classfile.ClassFormatException> but was: <java.lang.NullPointerException>
	at jp.skypencil.findbugs.slf4j.IllegalPassedClassDetectorTest.testFindClass(IllegalPassedClassDetectorTest.java:12)
Caused by: java.lang.NullPointerException
	at jp.skypencil.findbugs.slf4j.IllegalPassedClassDetectorTest.lambda$testFindClass$0(IllegalPassedClassDetectorTest.java:13)
	at jp.skypencil.findbugs.slf4j.IllegalPassedClassDetectorTest.testFindClass(IllegalPassedClassDetectorTest.java:12)
```

but I only hit this on `mvn clean install`, NOT when running the IllegalPassedClassDetectorTest in Eclipse.

The failure seems to make no sense - that `detector` there cannot be null ?!  

Very weird.

**Comment by KengoTODA** [comment]
Not reproducible for now. Please reopen if `master` branch still has this issue.
